#!/usr/bin/env python3
"""Generate the crawlable half of ThiagoTV.

The TV itself is a JavaScript application: it fetches playlist.json and paints
the screen. That's fine for a person, but a crawler fetching index.html sees an
empty div where the programme notes should be, and the LLM crawlers that matter
here (GPTBot, ClaudeBot, PerplexityBot) generally don't run JavaScript at all.

So the notes are also emitted as plain static HTML, one page per video, at
publish time. Those pages are the citable artefacts: each has its own URL, its
own title and description, and schema.org markup describing the video. The TV
stays the front door and links into them.

Everything under v/ and the files listed in GENERATED are outputs. Don't hand
edit them; edit playlist.json and run this again.

Usage:
    python3 scripts/build.py [--base-url https://example.com]
"""

import argparse
import datetime as dt
import html
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLAYLIST = ROOT / "playlist.json"
VIDEO_DIR = ROOT / "v"

GENERATED = ["guide.html", "notes.css", "sitemap.xml", "robots.txt"]

SECTIONS = [
    ("summary", "Summary"),
    ("relevance", "Why it matters"),
    ("controversy", "Controversy"),
]

STYLESHEET = """\
/* Generated by scripts/build.py -- edit the script, not this file. */
*, *::before, *::after { box-sizing: border-box; }
body {
  margin: 0;
  padding: 32px 20px 64px;
  background: radial-gradient(ellipse at 50% 0%, #1b3a6b 0%, #12244a 45%, #070f22 100%);
  background-attachment: fixed;
  font-family: 'Courier New', monospace;
  color: #2b2115;
}
.sheet {
  max-width: 760px;
  margin: 0 auto;
  background: linear-gradient(180deg, rgba(120,90,50,.10), transparent 220px), #efe4cd;
  padding: 44px 48px 36px;
  border-top: 1px solid #f7efdd;
  border-bottom: 1px solid #c5b391;
  box-shadow: 0 1px 0 rgba(255,255,255,.5) inset, 0 18px 44px rgba(0,0,0,.55);
}
.eyebrow {
  font-size: 11px; letter-spacing: 4px; text-transform: uppercase;
  color: #7a6444; margin: 0 0 8px;
}
h1 {
  font-family: Georgia, 'Times New Roman', serif;
  font-size: 28px; line-height: 1.25; margin: 0;
}
.meta {
  margin: 8px 0 0; font-size: 11px; letter-spacing: 2px;
  text-transform: uppercase; color: #7a6444;
}
.rule { border: 0; border-top: 2px solid #2b2115; margin: 14px 0 20px; }
h2 {
  font-size: 11px; letter-spacing: 3px; text-transform: uppercase;
  color: #8a2f1d; margin: 22px 0 7px;
}
p {
  font-family: Georgia, 'Times New Roman', serif;
  font-size: 15.5px; line-height: 1.72; margin: 0 0 10px;
}
.flagged { border-left: 3px solid #8a2f1d; padding-left: 14px; }
.empty { font-style: italic; color: #7a6444; }
.foot {
  margin-top: 28px; padding-top: 12px; border-top: 1px solid #c5b391;
  font-size: 10.5px; letter-spacing: 2px; text-transform: uppercase;
  color: #8a7a5c;
}
.foot a { color: #8a2f1d; }
.thumb { display: block; width: 100%; height: auto; margin-bottom: 22px; }
ul.programmes { list-style: none; padding: 0; margin: 0; }
ul.programmes li { border-bottom: 1px solid #d8c9a8; padding: 14px 0; }
ul.programmes li:last-child { border-bottom: 0; }
ul.programmes a {
  font-family: Georgia, 'Times New Roman', serif;
  font-size: 17px; color: #2b2115; text-decoration: none;
}
ul.programmes a:hover { text-decoration: underline; }
ul.programmes .tags {
  display: block; margin-top: 4px; font-size: 10.5px;
  letter-spacing: 2px; text-transform: uppercase; color: #7a6444;
}
@media (max-width: 700px) {
  .sheet { padding: 26px 22px 22px; }
  h1 { font-size: 21px; }
  p { font-size: 14px; line-height: 1.6; }
}
"""


def esc(text):
    return html.escape(str(text), quote=True)


def load_playlist():
    if not PLAYLIST.exists():
        sys.exit(f"{PLAYLIST} does not exist.")
    try:
        data = json.loads(PLAYLIST.read_text())
    except json.JSONDecodeError as exc:
        sys.exit(f"{PLAYLIST} is not valid JSON ({exc}).")
    return data


def summarise(video, limit=155):
    """A meta description: the first sentences of the summary, or a fallback."""
    doc = video.get("dossier") or {}
    text = (doc.get("summary") or "").strip()
    if not text:
        return f"{video.get('title', 'A video')} — programme notes from ThiagoTV."
    text = re.sub(r"\s+", " ", text)
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(" ", 1)[0]
    return cut + "…"


def paragraphs_html(text, flagged=False):
    cls = ' class="flagged"' if flagged else ""
    chunks = [c.strip() for c in re.split(r"\n{2,}", str(text)) if c.strip()]
    return "\n".join(f"<p{cls}>{esc(c)}</p>" for c in chunks)


def video_page(video, base_url, station):
    vid = video["videoId"]
    title = video.get("title", vid)
    doc = video.get("dossier") or {}
    # A canonical or og:url has to be absolute to mean anything. Without a real
    # origin, emitting a relative one points crawlers at nonsense, so we emit
    # nothing and let the build warn instead.
    canonical = f"{base_url}/v/{vid}.html" if base_url else ""
    thumb = f"https://i.ytimg.com/vi/{vid}/maxresdefault.jpg"
    description = summarise(video)
    tags = video.get("tags") or []

    body_parts = []
    for key, heading in SECTIONS:
        if doc.get(key):
            body_parts.append(f"<h2>{esc(heading)}</h2>")
            body_parts.append(paragraphs_html(doc[key], flagged=(key == "controversy")))
    if not body_parts:
        body_parts.append('<p class="empty">No notes on file for this one yet.</p>')

    # schema.org VideoObject. uploadDate is deliberately absent: the playlist
    # records when a video was scheduled here, not when it was published to
    # YouTube, and asserting the wrong date is worse than omitting the field.
    ld = {
        "@context": "https://schema.org",
        "@type": "VideoObject",
        "name": title,
        "description": description,
        "thumbnailUrl": thumb,
        "embedUrl": f"https://www.youtube.com/embed/{vid}",
        "url": canonical or None,
        "keywords": ", ".join(tags) if tags else None,
        "isPartOf": {
            "@type": "CreativeWork",
            "name": station.get("title", "ThiagoTV"),
            **({"url": base_url} if base_url else {}),
        },
    }
    ld = {k: v for k, v in ld.items() if v is not None}

    meta_bits = []
    if tags:
        meta_bits.append(esc(" · ".join(tags)))
    if video.get("addedAt"):
        meta_bits.append("Aired " + esc(video["addedAt"]))

    home = f"{base_url}/" if base_url else "../index.html"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)} — {esc(station.get('title', 'ThiagoTV'))}</title>
<meta name="description" content="{esc(description)}">
{f'<link rel="canonical" href="{esc(canonical)}">' if canonical else ''}
<link rel="stylesheet" href="../notes.css">
<meta property="og:type" content="video.other">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:image" content="{esc(thumb)}">
{f'<meta property="og:url" content="{esc(canonical)}">' if canonical else ''}
<meta name="twitter:card" content="summary_large_image">
<script type="application/ld+json">
{json.dumps(ld, indent=2, ensure_ascii=False)}
</script>
</head>
<body>
<main class="sheet">
<img class="thumb" src="{esc(thumb)}" alt="" loading="lazy">
<p class="eyebrow">Programme notes</p>
<h1>{esc(title)}</h1>
<p class="meta">{'  //  '.join(meta_bits)}</p>
<hr class="rule">
{chr(10).join(body_parts)}
<footer class="foot">
<p><a href="{esc(home)}">← Back to ThiagoTV</a></p>
<p><a href="https://www.youtube.com/watch?v={esc(vid)}" rel="noopener">Watch on YouTube</a></p>
</footer>
</main>
</body>
</html>
"""


def guide_page(videos, base_url, station):
    canonical = f"{base_url}/guide.html" if base_url else ""
    home = f"{base_url}/" if base_url else "index.html"

    items = []
    for video in videos:
        vid = video["videoId"]
        tags = video.get("tags") or []
        items.append(
            f'<li><a href="v/{esc(vid)}.html">{esc(video.get("title", vid))}</a>'
            f'<span class="tags">{esc(" · ".join(tags)) or "untagged"}</span></li>'
        )

    ld = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": f"Programme guide — {station.get('title', 'ThiagoTV')}",
        **({"url": canonical} if canonical else {}),
        "hasPart": [
            {
                "@type": "VideoObject",
                "name": v.get("title", v["videoId"]),
                "url": (f"{base_url}/v/{v['videoId']}.html" if base_url
                        else f"v/{v['videoId']}.html"),
            }
            for v in videos
        ],
    }

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Programme guide — {esc(station.get('title', 'ThiagoTV'))}</title>
<meta name="description" content="Every programme broadcast on {esc(station.get('title', 'ThiagoTV'))}, with notes on what each one is and why it matters.">
{f'<link rel="canonical" href="{esc(canonical)}">' if canonical else ''}
<link rel="stylesheet" href="notes.css">
<script type="application/ld+json">
{json.dumps(ld, indent=2, ensure_ascii=False)}
</script>
</head>
<body>
<main class="sheet">
<p class="eyebrow">{esc(station.get('title', 'ThiagoTV'))}</p>
<h1>Programme guide</h1>
<p class="meta">{len(videos)} programmes on file</p>
<hr class="rule">
<ul class="programmes">
{chr(10).join(items)}
</ul>
<footer class="foot">
<p><a href="{esc(home)}">← Back to ThiagoTV</a></p>
</footer>
</main>
</body>
</html>
"""


def sitemap(videos, base_url):
    today = dt.date.today().isoformat()
    urls = [f"{base_url}/", f"{base_url}/guide.html"]
    urls += [f"{base_url}/v/{v['videoId']}.html" for v in videos]
    entries = "\n".join(
        f"  <url><loc>{esc(u)}</loc><lastmod>{today}</lastmod></url>" for u in urls
    )
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{entries}
</urlset>
"""


def robots(base_url):
    # Answering LLM crawlers explicitly rather than by omission: the notes exist
    # to be read and cited, so the crawlers that do that are welcomed by name.
    return f"""User-agent: *
Allow: /

User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

Sitemap: {base_url}/sitemap.xml
"""


def main():
    parser = argparse.ArgumentParser(description="Generate ThiagoTV's static pages.")
    parser.add_argument("--base-url", help="e.g. https://thiagotv.vercel.app "
                                           "(default: the 'site.url' in playlist.json)")
    args = parser.parse_args()

    data = load_playlist()
    station = data.get("site") or {}
    base_url = (args.base_url or station.get("url") or "").rstrip("/")
    videos = [v for v in data.get("playlist", []) if v.get("videoId")]
    videos.sort(key=lambda v: str(v.get("addedAt", "")), reverse=True)

    if VIDEO_DIR.exists():
        shutil.rmtree(VIDEO_DIR)
    VIDEO_DIR.mkdir(parents=True)

    for video in videos:
        (VIDEO_DIR / f"{video['videoId']}.html").write_text(
            video_page(video, base_url, station)
        )

    (ROOT / "notes.css").write_text(STYLESHEET)
    (ROOT / "guide.html").write_text(guide_page(videos, base_url, station))

    if base_url:
        (ROOT / "sitemap.xml").write_text(sitemap(videos, base_url))
        (ROOT / "robots.txt").write_text(robots(base_url))
    else:
        # Without a real origin these two files would advertise wrong URLs, which
        # is worse than not shipping them.
        for name in ("sitemap.xml", "robots.txt"):
            (ROOT / name).unlink(missing_ok=True)

    with_notes = sum(1 for v in videos if (v.get("dossier") or {}))
    print(f"Built {len(videos)} programme pages ({with_notes} with notes), guide.html")
    if base_url:
        print(f"       sitemap.xml and robots.txt for {base_url}")
    else:
        print("       no site.url set -- skipped sitemap.xml and robots.txt.")
        print('       Set it with: "site": {"url": "https://..."} in playlist.json')


if __name__ == "__main__":
    main()
