#!/usr/bin/env python3
"""Generate the crawlable half of ThiagoTV.

The TV itself is a JavaScript application: it fetches playlist.json and paints
the screen. That's fine for a person, but a crawler fetching index.html sees an
empty div where the programme notes should be, and the LLM crawlers that matter
here (GPTBot, ClaudeBot, PerplexityBot) generally don't run JavaScript at all.

So the notes are also emitted as plain static HTML, one page per video, at
publish time. Those pages are the citable artefacts: each has its own URL, its
own title and description, and schema.org markup describing the video. The TV
stays the front door and links into them.

Everything under v/ and the files listed in GENERATED are outputs. Don't hand
edit them; edit playlist.json and run this again.

Usage:
    python3 scripts/build.py [--base-url https://example.com]
"""

import argparse
import datetime as dt
import html
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLAYLIST = ROOT / "playlist.json"
VIDEO_DIR = ROOT / "v"
CHANNEL_DIR = ROOT / "c"

GENERATED = ["guide.html", "notes.css", "sitemap.xml", "robots.txt"]

SECTIONS = [
    ("summary", "Summary"),
    ("relevance", "Why it matters"),
    ("controversy", "Controversy"),
]

MONTH_NAMES = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

WATCHED_SCRIPT = '''<script>
/* Marks what this visitor has already watched, reading the same localStorage the
   set writes. Kept out of the generated HTML on purpose: the page is identical
   for everyone and for crawlers, and the personal layer is added client-side. */
(function () {
  var seen;
  try {
    seen = JSON.parse(localStorage.getItem('thiagotv.seen.v1') || '{}');
  } catch (e) { return; }

  var resume;
  try {
    resume = JSON.parse(localStorage.getItem('thiagotv.resume.v1') || '{}');
  } catch (e) { resume = {}; }

  // Only real programmes -- the date headings are list items too, and counting
  // them would inflate the total.
  var items = document.querySelectorAll('#programmes li[data-id]');
  var watched = 0;

  Array.prototype.forEach.call(items, function (li) {
    var id = li.getAttribute('data-id');
    var part = resume[id];
    // Part-watched is more useful to say than watched: it's the thing you might
    // want to go back to.
    // Not every row carries a tag line -- on a channel page it only appears
    // when the programme is also on another channel -- so the mark goes after
    // the title when there's nowhere else for it.
    var slot = li.querySelector('.tags') || li.querySelector('a');
    if (part && typeof part.t === 'number' && part.t > 30) {
      li.classList.add('part-watched');
      var m = Math.floor(part.t / 60), s = Math.floor(part.t % 60);
      slot.insertAdjacentHTML(
        'afterend',
        ' <em class="mark">stopped at ' + m + ':' + (s < 10 ? '0' : '') + s + '</em>'
      );
      watched++;
      return;
    }
    if (Object.prototype.hasOwnProperty.call(seen, id)) {
      li.classList.add('watched');
      slot.insertAdjacentHTML('afterend', ' <em class="mark">watched</em>');
      watched++;
    }
  });

  var summary = document.getElementById('watchedSummary');
  if (summary && items.length) {
    summary.textContent = watched
      ? 'You have watched ' + watched + ' of ' + items.length + ' programmes.'
      : '';
  }
})();
</script>'''

STYLESHEET = """\
/* Generated by scripts/build.py -- edit the script, not this file. */
*, *::before, *::after { box-sizing: border-box; }
body {
  margin: 0;
  padding: 32px 20px 64px;
  background: radial-gradient(ellipse at 50% 0%, #1b3a6b 0%, #12244a 45%, #070f22 100%);
  background-attachment: fixed;
  font-family: 'Courier New', monospace;
  color: #2b2115;
}
.sheet {
  max-width: 760px;
  margin: 0 auto;
  background: linear-gradient(180deg, rgba(120,90,50,.10), transparent 220px), #efe4cd;
  padding: 44px 48px 36px;
  border-top: 1px solid #f7efdd;
  border-bottom: 1px solid #c5b391;
  box-shadow: 0 1px 0 rgba(255,255,255,.5) inset, 0 18px 44px rgba(0,0,0,.55);
}
.eyebrow {
  font-size: 11px; letter-spacing: 4px; text-transform: uppercase;
  color: #7a6444; margin: 0 0 8px;
}
h1 {
  font-family: Georgia, 'Times New Roman', serif;
  font-size: 28px; line-height: 1.25; margin: 0;
}
.meta {
  margin: 8px 0 0; font-size: 11px; letter-spacing: 2px;
  text-transform: uppercase; color: #7a6444;
}
.rule { border: 0; border-top: 2px solid #2b2115; margin: 14px 0 20px; }
h2 {
  font-size: 11px; letter-spacing: 3px; text-transform: uppercase;
  color: #8a2f1d; margin: 22px 0 7px;
}
p {
  font-family: Georgia, 'Times New Roman', serif;
  font-size: 15.5px; line-height: 1.72; margin: 0 0 10px;
}
.flagged { border-left: 3px solid #8a2f1d; padding-left: 14px; }
.empty { font-style: italic; color: #7a6444; }
.foot {
  margin-top: 28px; padding-top: 12px; border-top: 1px solid #c5b391;
  font-size: 10.5px; letter-spacing: 2px; text-transform: uppercase;
  color: #8a7a5c;
}
.foot a { color: #8a2f1d; }
.thumb { display: block; width: 100%; height: auto; margin-bottom: 22px; }
/* The programme itself, so the page is somewhere to watch rather than only to
   read about. Loaded lazily and from the no-cookie host: a page of notes has no
   business setting tracking cookies before anyone presses play. */
.player {
  position: relative;
  width: 100%;
  aspect-ratio: 16 / 9;
  margin-bottom: 24px;
  background: #05070a;
  box-shadow: 0 0 0 6px #241408, 0 10px 26px rgba(0,0,0,.5);
}
.player iframe {
  position: absolute; inset: 0;
  width: 100%; height: 100%; border: 0;
}
ul.programmes { list-style: none; padding: 0; margin: 0; }
ul.programmes li { border-bottom: 1px solid #d8c9a8; padding: 14px 0; }
ul.programmes li:last-child { border-bottom: 0; }
ul.programmes a {
  font-family: Georgia, 'Times New Roman', serif;
  font-size: 17px; color: #2b2115; text-decoration: none;
}
ul.programmes a:hover { text-decoration: underline; }
ul.programmes .tags {
  display: block; margin-top: 4px; font-size: 10.5px;
  letter-spacing: 2px; text-transform: uppercase; color: #7a6444;
}
/* Already-watched entries recede; the ones still to see stay at full strength. */
ul.programmes li.watched a { color: #7a6444; }
ul.programmes li.part-watched a { color: #2b2115; }
ul.programmes .mark {
  font-style: normal; margin-left: 8px; padding: 1px 5px;
  background: #ded0b2; color: #6a5636; border-radius: 2px; letter-spacing: 1px;
}
ul.programmes li.part-watched .mark { background: #8a2f1d; color: #f3e7d2; }

/* ---- Calendar archive ---- */
.archive { margin-bottom: 26px; }
.archive > h2 {
  font-size: 11px; letter-spacing: 3px; text-transform: uppercase;
  color: #8a2f1d; margin: 0 0 12px;
}
.cal-month { margin-bottom: 16px; }
.cal-month h3 {
  font-family: Georgia, 'Times New Roman', serif;
  font-size: 15px; font-weight: normal; margin: 0 0 7px; color: #4a3a24;
}
.cal-days { display: flex; flex-wrap: wrap; gap: 6px; }
.cal-day {
  display: flex; flex-direction: column; align-items: center; justify-content: center;
  min-width: 42px; padding: 5px 6px;
  background: #e2d4b6; border: 1px solid #cbb894;
  text-decoration: none; color: #2b2115; line-height: 1.15;
}
.cal-day:hover { background: #d3c09b; }
.cal-num { font-size: 14px; font-weight: bold; }
.cal-count {
  font-size: 9px; letter-spacing: 1px; text-transform: uppercase; color: #7a6444;
}
li.date-row { border-bottom: 0 !important; padding: 22px 0 4px !important; }
li.date-row h2 {
  font-size: 11px; letter-spacing: 3px; text-transform: uppercase;
  color: #8a2f1d; margin: 0; display: flex; gap: 10px; align-items: baseline;
}
li.date-row:first-child { padding-top: 0 !important; }
.date-count { font-size: 10px; color: #a08a63; letter-spacing: 1px; }
a.tag-link { color: #8a2f1d; text-decoration: none; border-bottom: 1px dotted #b9917f; }
a.tag-link:hover { background: #e6d6b4; }
@media (max-width: 700px) {
  .sheet { padding: 26px 22px 22px; }
  h1 { font-size: 21px; }
  p { font-size: 14px; line-height: 1.6; }
}
"""


def esc(text):
    return html.escape(str(text), quote=True)


def load_playlist():
    if not PLAYLIST.exists():
        sys.exit(f"{PLAYLIST} does not exist.")
    try:
        data = json.loads(PLAYLIST.read_text())
    except json.JSONDecodeError as exc:
        sys.exit(f"{PLAYLIST} is not valid JSON ({exc}).")
    return data


def summarise(video, limit=155):
    """A meta description: the first sentences of the summary, or a fallback."""
    doc = video.get("dossier") or {}
    text = (doc.get("summary") or "").strip()
    if not text:
        return f"{video.get('title', 'A video')} — programme notes from ThiagoTV."
    text = re.sub(r"\s+", " ", text)
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(" ", 1)[0]
    return cut + "…"


def paragraphs_html(text, flagged=False):
    cls = ' class="flagged"' if flagged else ""
    chunks = [c.strip() for c in re.split(r"\n{2,}", str(text)) if c.strip()]
    return "\n".join(f"<p{cls}>{esc(c)}</p>" for c in chunks)


def video_page(video, base_url, station):
    vid = video["videoId"]
    title = video.get("title", vid)
    doc = video.get("dossier") or {}
    # A canonical or og:url has to be absolute to mean anything. Without a real
    # origin, emitting a relative one points crawlers at nonsense, so we emit
    # nothing and let the build warn instead.
    canonical = f"{base_url}/v/{vid}.html" if base_url else ""
    thumb = f"https://i.ytimg.com/vi/{vid}/maxresdefault.jpg"
    description = summarise(video)
    tags = video.get("tags") or []

    body_parts = []
    for key, heading in SECTIONS:
        if doc.get(key):
            body_parts.append(f"<h2>{esc(heading)}</h2>")
            body_parts.append(paragraphs_html(doc[key], flagged=(key == "controversy")))
    if not body_parts:
        body_parts.append('<p class="empty">No notes on file for this one yet.</p>')

    # schema.org VideoObject. uploadDate is deliberately absent: the playlist
    # records when a video was scheduled here, not when it was published to
    # YouTube, and asserting the wrong date is worse than omitting the field.
    ld = {
        "@context": "https://schema.org",
        "@type": "VideoObject",
        "name": title,
        "description": description,
        "thumbnailUrl": thumb,
        "embedUrl": f"https://www.youtube.com/embed/{vid}",
        "url": canonical or None,
        "keywords": ", ".join(tags) if tags else None,
        "isPartOf": {
            "@type": "CreativeWork",
            "name": station.get("title", "ThiagoTV"),
            **({"url": base_url} if base_url else {}),
        },
    }
    ld = {k: v for k, v in ld.items() if v is not None}

    meta_bits = []
    if tags:
        meta_bits.append(esc(" · ".join(tags)))
    if video.get("addedAt"):
        meta_bits.append("Aired " + esc(video["addedAt"]))

    home = f"{base_url}/" if base_url else "../index.html"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)} — {esc(station.get('title', 'ThiagoTV'))}</title>
<meta name="description" content="{esc(description)}">
{f'<link rel="canonical" href="{esc(canonical)}">' if canonical else ''}
<link rel="stylesheet" href="../notes.css">
<meta property="og:type" content="video.other">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:image" content="{esc(thumb)}">
{f'<meta property="og:url" content="{esc(canonical)}">' if canonical else ''}
<meta name="twitter:card" content="summary_large_image">
<script type="application/ld+json">
{json.dumps(ld, indent=2, ensure_ascii=False)}
</script>
</head>
<body>
<main class="sheet">
<div class="player">
<iframe src="https://www.youtube-nocookie.com/embed/{esc(vid)}"
        title="{esc(title)}"
        loading="lazy"
        allow="accelerometer; encrypted-media; gyroscope; picture-in-picture"
        referrerpolicy="strict-origin-when-cross-origin"
        allowfullscreen></iframe>
</div>
<p class="eyebrow">Programme notes</p>
<h1>{esc(title)}</h1>
<p class="meta">{'  //  '.join(meta_bits)}</p>
<hr class="rule">
{chr(10).join(body_parts)}
<footer class="foot">
<p><a href="{esc(home)}">← Back to ThiagoTV</a></p>
<p><a href="https://www.youtube.com/watch?v={esc(vid)}" rel="noopener">Watch on YouTube</a></p>
</footer>
</main>
</body>
</html>
"""


def tag_links(tags, prefix=""):
    """Tags rendered as links to their channel archive."""
    if not tags:
        return "untagged"
    return " · ".join(
        f'<a class="tag-link" href="{prefix}c/{esc(t)}.html">{esc(t)}</a>' for t in tags
    )


def channel_page(tag, videos, base_url, station):
    """One page per channel: everything that channel carries, newest first.

    The guide answers "what aired when"; these answer "what is on this channel",
    which is the question someone arriving from a search actually has.
    """
    canonical = f"{base_url}/c/{tag}.html" if base_url else ""
    home = f"{base_url}/" if base_url else "../index.html"
    guide = f"{base_url}/guide.html" if base_url else "../guide.html"

    items = []
    for video in videos:
        vid = video["videoId"]
        others = [t for t in (video.get("tags") or []) if t != tag]
        extra = f'<span class="tags">also on {tag_links(others, "../")}</span>' if others else ""
        items.append(
            f'<li data-id="{esc(vid)}">'
            f'<a href="../v/{esc(vid)}.html">{esc(video.get("title", vid))}</a>{extra}</li>'
        )

    described = sum(1 for v in videos if (v.get("dossier") or {}))
    ld = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": f"{tag.title()} — {station.get('title', 'ThiagoTV')}",
        **({"url": canonical} if canonical else {}),
        "hasPart": [
            {
                "@type": "VideoObject",
                "name": v.get("title", v["videoId"]),
                **({"url": f"{base_url}/v/{v['videoId']}.html"} if base_url else {}),
            }
            for v in videos
        ],
    }

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(tag.title())} — {esc(station.get('title', 'ThiagoTV'))}</title>
<meta name="description" content="Everything on the {esc(tag)} channel of {esc(station.get('title', 'ThiagoTV'))} — {len(videos)} programmes, {described} with notes.">
{f'<link rel="canonical" href="{esc(canonical)}">' if canonical else ''}
<link rel="stylesheet" href="../notes.css">
<script type="application/ld+json">
{json.dumps(ld, indent=2, ensure_ascii=False)}
</script>
</head>
<body>
<main class="sheet">
<p class="eyebrow">Channel</p>
<h1>{esc(tag.title())}</h1>
<p class="meta">{len(videos)} programmes · {described} with notes</p>
<hr class="rule">
<ul class="programmes" id="programmes">
{chr(10).join(items)}
</ul>
<footer class="foot">
<p><a href="{esc(home)}">← Back to ThiagoTV</a></p>
<p><a href="{esc(guide)}">Programme guide</a></p>
</footer>
</main>
{WATCHED_SCRIPT}
</body>
</html>
"""


def guide_page(videos, base_url, station):
    canonical = f"{base_url}/guide.html" if base_url else ""
    home = f"{base_url}/" if base_url else "index.html"

    # Group by airdate so the guide reads as an archive rather than one long list.
    # With hundreds of programmes, a flat list is unusable: the calendar is the
    # only way to find "the thing from that Friday".
    by_date = {}
    for video in videos:
        by_date.setdefault(str(video.get("addedAt") or "undated"), []).append(video)
    dates = sorted(by_date, reverse=True)

    # The calendar strip: months, each showing the days that carry programmes.
    months = {}
    for date in dates:
        months.setdefault(date[:7] if date != "undated" else "undated", []).append(date)

    cal_blocks = []
    for month in sorted(months, reverse=True):
        if month == "undated":
            label = "Undated"
        else:
            y, m = month.split("-")
            label = f"{MONTH_NAMES[int(m) - 1]} {y}"
        days = []
        for date in months[month]:
            n = len(by_date[date])
            day = date[8:10] if date != "undated" else "?"
            days.append(
                f'<a class="cal-day" href="#d-{esc(date)}">'
                f'<span class="cal-num">{esc(day.lstrip("0") or day)}</span>'
                f'<span class="cal-count">{n}</span></a>'
            )
        cal_blocks.append(
            f'<div class="cal-month"><h3>{esc(label)}</h3>'
            f'<div class="cal-days">{"".join(days)}</div></div>'
        )

    items = []
    for date in dates:
        group = by_date[date]
        if date == "undated":
            heading = "Undated"
        else:
            y, m, d = date.split("-")
            heading = f"{d.lstrip('0')} {MONTH_NAMES[int(m) - 1]} {y}"
        items.append(
            f'<li class="date-row" id="d-{esc(date)}">'
            f'<h2>{esc(heading)}<span class="date-count">{len(group)}</span></h2></li>'
        )
        for video in group:
            vid = video["videoId"]
            tags = video.get("tags") or []
            # data-id lets the guide mark what this visitor has already watched. The
            # marking happens in their browser, from the same localStorage the set
            # uses, so the page itself stays static and identical for everyone.
            items.append(
                f'<li data-id="{esc(vid)}">'
                f'<a href="v/{esc(vid)}.html">{esc(video.get("title", vid))}</a>'
                f'<span class="tags">{tag_links(tags)}</span></li>'
            )

    ld = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": f"Programme guide — {station.get('title', 'ThiagoTV')}",
        **({"url": canonical} if canonical else {}),
        "hasPart": [
            {
                "@type": "VideoObject",
                "name": v.get("title", v["videoId"]),
                "url": (f"{base_url}/v/{v['videoId']}.html" if base_url
                        else f"v/{v['videoId']}.html"),
            }
            for v in videos
        ],
    }

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Programme guide — {esc(station.get('title', 'ThiagoTV'))}</title>
<meta name="description" content="Every programme broadcast on {esc(station.get('title', 'ThiagoTV'))}, with notes on what each one is and why it matters.">
{f'<link rel="canonical" href="{esc(canonical)}">' if canonical else ''}
<link rel="stylesheet" href="notes.css">
<script type="application/ld+json">
{json.dumps(ld, indent=2, ensure_ascii=False)}
</script>
</head>
<body>
<main class="sheet">
<p class="eyebrow">{esc(station.get('title', 'ThiagoTV'))}</p>
<h1>Programme guide</h1>
<p class="meta">{len(videos)} programmes on file · {len(dates)} broadcast {"day" if len(dates) == 1 else "days"}</p>
<hr class="rule">
<nav class="archive">
<h2>Archive</h2>
{chr(10).join(cal_blocks)}
</nav>
<ul class="programmes" id="programmes">
{chr(10).join(items)}
</ul>
<footer class="foot">
<p><a href="{esc(home)}">← Back to ThiagoTV</a></p>
<p id="watchedSummary"></p>
</footer>
</main>
{WATCHED_SCRIPT}
</body>
</html>
"""


def sitemap(videos, base_url, tags=()):
    today = dt.date.today().isoformat()
    urls = [f"{base_url}/", f"{base_url}/guide.html"]
    urls += [f"{base_url}/c/{t}.html" for t in tags]
    urls += [f"{base_url}/v/{v['videoId']}.html" for v in videos]
    entries = "\n".join(
        f"  <url><loc>{esc(u)}</loc><lastmod>{today}</lastmod></url>" for u in urls
    )
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{entries}
</urlset>
"""


def robots(base_url):
    # Answering LLM crawlers explicitly rather than by omission: the notes exist
    # to be read and cited, so the crawlers that do that are welcomed by name.
    return f"""User-agent: *
Allow: /

User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

Sitemap: {base_url}/sitemap.xml
"""


def main():
    parser = argparse.ArgumentParser(description="Generate ThiagoTV's static pages.")
    parser.add_argument("--base-url", help="e.g. https://thiagotv.vercel.app "
                                           "(default: the 'site.url' in playlist.json)")
    args = parser.parse_args()

    data = load_playlist()
    station = data.get("site") or {}
    base_url = (args.base_url or station.get("url") or "").rstrip("/")
    videos = [v for v in data.get("playlist", []) if v.get("videoId")]
    videos.sort(key=lambda v: str(v.get("addedAt", "")), reverse=True)

    if VIDEO_DIR.exists():
        shutil.rmtree(VIDEO_DIR)
    VIDEO_DIR.mkdir(parents=True)

    for video in videos:
        (VIDEO_DIR / f"{video['videoId']}.html").write_text(
            video_page(video, base_url, station)
        )

    (ROOT / "notes.css").write_text(STYLESHEET)
    (ROOT / "guide.html").write_text(guide_page(videos, base_url, station))

    # One page per channel. Rebuilt from scratch so a tag that stops being used
    # doesn't leave an orphan page behind advertising programmes it no longer has.
    if CHANNEL_DIR.exists():
        shutil.rmtree(CHANNEL_DIR)
    CHANNEL_DIR.mkdir(parents=True)
    tags = sorted({t for v in videos for t in (v.get("tags") or [])})
    for tag in tags:
        carried = [v for v in videos if tag in (v.get("tags") or [])]
        (CHANNEL_DIR / f"{tag}.html").write_text(
            channel_page(tag, carried, base_url, station)
        )

    if base_url:
        (ROOT / "sitemap.xml").write_text(sitemap(videos, base_url, tags))
        (ROOT / "robots.txt").write_text(robots(base_url))
    else:
        # Without a real origin these two files would advertise wrong URLs, which
        # is worse than not shipping them.
        for name in ("sitemap.xml", "robots.txt"):
            (ROOT / name).unlink(missing_ok=True)

    with_notes = sum(1 for v in videos if (v.get("dossier") or {}))
    print(f"Built {len(videos)} programme pages ({with_notes} with notes), "
          f"{len(tags)} channel pages, guide.html")
    if base_url:
        print(f"       sitemap.xml and robots.txt for {base_url}")
    else:
        print("       no site.url set -- skipped sitemap.xml and robots.txt.")
        print('       Set it with: "site": {"url": "https://..."} in playlist.json')


if __name__ == "__main__":
    main()
